 Simple Webscraping

In [3]:
import requests
from bs4 import BeautifulSoup

In [4]:
url= "https://www.scrapethissite.com/pages/forms/"
response = requests.get(url)
print(response.status_code)

200

In [5]:
soup = BeautifulSoup(response.text,"html.parser")
print(soup)

<!DOCTYPE html>

<html lang="en">
<head>
<meta charset="utf-8"/>
<title>Hockey Teams: Forms, Searching and Pagination | Scrape This Site | A public sandbox for learning web scraping</title>
<link href="/static/images/scraper-icon.png" rel="icon" type="image/png"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<meta content="Browse through a database of NHL team stats since 1990. Practice building a scraper that handles common website interface components." name="description"/>
<link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css?family=Lato:400,700" rel="stylesheet" type="text/css"/>
<link href="/static/css/styles.css" rel="stylesheet" type="text/css"/>
<meta content="noindex" name="robots"/>
</head>
<body>
<nav id="site-nav">
<div class="container">
<div class="col-md-12">
<ul class="nav nav-tabs">
<li id="nav-homepage">
<a class="nav-link hidden-sm hidden-xs" href="/">
<img id="nav-logo" src="/static/images/scraper-icon.png"/>
                                Scrape This Site
                            </a>
</li>
<li id="nav-sandbox">
<a class="nav-link" href="/pages/">
<i class="glyphicon glyphicon-console hidden-sm hidden-xs"></i>
                                Sandbox
                            </a>
</li>
<li id="nav-lessons">
<a class="nav-link" href="/lessons/">
<i class="glyphicon glyphicon-education hidden-sm hidden-xs"></i>
                                Lessons
                            </a>
</li>
<li id="nav-faq">
<a class="nav-link" href="/faq/">
<i class="glyphicon glyphicon-flag hidden-sm hidden-xs"></i>
                                FAQ
                            </a>
</li>
<li class="pull-right" id="nav-login">
<a class="nav-link" href="/login/">
                                Login
                            </a>
</li>
</ul>
</div>
</div>
</nav>
<script type="text/javascript">
            var path = document.location.pathname;
            var tab = undefined;
            if (path === "/"){
                tab = document.querySelector("#nav-homepage");
            } else if (path.indexOf("/faq/") === 0){
                tab = document.querySelector("#nav-faq");
            } else if (path.indexOf("/lessons/") === 0){
                tab = document.querySelector("#nav-lessons");
            } else if (path.indexOf("/pages/") === 0) {
                tab = document.querySelector("#nav-sandbox");
            } else if (path.indexOf("/login/") === 0) {
                tab = document.querySelector("#nav-login");
            }
            tab.classList.add("active")
        </script>
<div id="page">
<section id="hockey">
<div class="container">
<div class="row">
<div class="col-md-12">
<h1>
                            Hockey Teams: Forms, Searching and Pagination
                            <small>25 items</small>
</h1>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-12">
<p class="lead">
                            Browse through a database of NHL team stats since 1990. Practice building a scraper that handles common website interface components.
                            Take a look at how pagination and search elements change the URL as your browse. Build a web scraper that can conduct searches and paginate through the results.
                        </p>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-6">
<p>
<i class="glyphicon glyphicon-education"></i> There are <a href="/lessons/">8 video lessons</a> that show you how to scrape this page.
                        </p>
<hr/>
</div>
<div class="col-md-6 text-right">
<p>

                                Data via
                                <a class="data-attribution" href="http://www.opensourcesports.com/hockey/" target="_blank">http://www.opensourcesports.com/hockey/</a>
</p>
<hr/>
</div>
</div>
<div class="row search-area">
<div class="col-md-12 text-center">
<form action="/pages/forms/" class="form form-inline" method="GET">
<label for="q">
                                Search for Teams:
                            </label>
<input class="form-control" id="q" name="q" placeholder="Search for Teams" type="text"/>
<input class="btn btn-primary" type="submit" value="Search"/>
</form>
<hr/>
</div>
</div><!--.row.search-area-->
<table class="table">
<tr>
<th>
                            Team Name
                        </th>
<th>
                            Year
                        </th>
<th>
                            Wins
                        </th>
<th>
                            Losses
                        </th>
<th>
                            OT Losses
                        </th>
<th>
                            Win %
                        </th>
<th>
                            Goals For (GF)
                        </th>
<th>
                            Goals Against (GA)
                        </th>
<th>
                            + / -
                        </th>
</tr>
<tr class="team">
<td class="name">
                            Boston Bruins
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            44
                        </td>
<td class="losses">
                            24
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.55
                        </td>
<td class="gf">
                            299
                        </td>
<td class="ga">
                            264
                        </td>
<td class="diff text-success">
                            35
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Buffalo Sabres
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            31
                        </td>
<td class="losses">
                            30
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.388
                        </td>
<td class="gf">
                            292
                        </td>
<td class="ga">
                            278
                        </td>
<td class="diff text-success">
                            14
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Calgary Flames
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            46
                        </td>
<td class="losses">
                            26
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.575
                        </td>
<td class="gf">
                            344
                        </td>
<td class="ga">
                            263
                        </td>
<td class="diff text-success">
                            81
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Chicago Blackhawks
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            49
                        </td>
<td class="losses">
                            23
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.613
                        </td>
<td class="gf">
                            284
                        </td>
<td class="ga">
                            211
                        </td>
<td class="diff text-success">
                            73
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Detroit Red Wings
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            34
                        </td>
<td class="losses">
                            38
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.425
                        </td>
<td class="gf">
                            273
                        </td>
<td class="ga">
                            298
                        </td>
<td class="diff text-danger">
                            -25
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Edmonton Oilers
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            37
                        </td>
<td class="losses">
                            37
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.463
                        </td>
<td class="gf">
                            272
                        </td>
<td class="ga">
                            272
                        </td>
<td class="diff text-success">
                            0
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Hartford Whalers
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            31
                        </td>
<td class="losses">
                            38
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.388
                        </td>
<td class="gf">
                            238
                        </td>
<td class="ga">
                            276
                        </td>
<td class="diff text-danger">
                            -38
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Los Angeles Kings
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            46
                        </td>
<td class="losses">
                            24
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.575
                        </td>
<td class="gf">
                            340
                        </td>
<td class="ga">
                            254
                        </td>
<td class="diff text-success">
                            86
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Minnesota North Stars
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            27
                        </td>
<td class="losses">
                            39
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.338
                        </td>
<td class="gf">
                            256
                        </td>
<td class="ga">
                            266
                        </td>
<td class="diff text-danger">
                            -10
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Montreal Canadiens
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            39
                        </td>
<td class="losses">
                            30
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.487
                        </td>
<td class="gf">
                            273
                        </td>
<td class="ga">
                            249
                        </td>
<td class="diff text-success">
                            24
                        </td>
</tr>
<tr class="team">
<td class="name">
                            New Jersey Devils
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            32
                        </td>
<td class="losses">
                            33
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.4
                        </td>
<td class="gf">
                            272
                        </td>
<td class="ga">
                            264
                        </td>
<td class="diff text-success">
                            8
                        </td>
</tr>
<tr class="team">
<td class="name">
                            New York Islanders
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            25
                        </td>
<td class="losses">
                            45
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.312
                        </td>
<td class="gf">
                            223
                        </td>
<td class="ga">
                            290
                        </td>
<td class="diff text-danger">
                            -67
                        </td>
</tr>
<tr class="team">
<td class="name">
                            New York Rangers
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            36
                        </td>
<td class="losses">
                            31
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.45
                        </td>
<td class="gf">
                            297
                        </td>
<td class="ga">
                            265
                        </td>
<td class="diff text-success">
                            32
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Philadelphia Flyers
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            33
                        </td>
<td class="losses">
                            37
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.412
                        </td>
<td class="gf">
                            252
                        </td>
<td class="ga">
                            267
                        </td>
<td class="diff text-danger">
                            -15
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Pittsburgh Penguins
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            41
                        </td>
<td class="losses">
                            33
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.512
                        </td>
<td class="gf">
                            342
                        </td>
<td class="ga">
                            305
                        </td>
<td class="diff text-success">
                            37
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Quebec Nordiques
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            16
                        </td>
<td class="losses">
                            50
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.2
                        </td>
<td class="gf">
                            236
                        </td>
<td class="ga">
                            354
                        </td>
<td class="diff text-danger">
                            -118
                        </td>
</tr>
<tr class="team">
<td class="name">
                            St. Louis Blues
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            47
                        </td>
<td class="losses">
                            22
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.588
                        </td>
<td class="gf">
                            310
                        </td>
<td class="ga">
                            250
                        </td>
<td class="diff text-success">
                            60
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Toronto Maple Leafs
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            23
                        </td>
<td class="losses">
                            46
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.287
                        </td>
<td class="gf">
                            241
                        </td>
<td class="ga">
                            318
                        </td>
<td class="diff text-danger">
                            -77
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Vancouver Canucks
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            28
                        </td>
<td class="losses">
                            43
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.35
                        </td>
<td class="gf">
                            243
                        </td>
<td class="ga">
                            315
                        </td>
<td class="diff text-danger">
                            -72
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Washington Capitals
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            37
                        </td>
<td class="losses">
                            36
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.463
                        </td>
<td class="gf">
                            258
                        </td>
<td class="ga">
                            258
                        </td>
<td class="diff text-success">
                            0
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Winnipeg Jets
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">

In [6]:
print(soup.prettify())

<!DOCTYPE html>
<html lang="en">
 <head>
  <meta charset="utf-8"/>
  <title>
   Hockey Teams: Forms, Searching and Pagination | Scrape This Site | A public sandbox for learning web scraping
  </title>
  <link href="/static/images/scraper-icon.png" rel="icon" type="image/png"/>
  <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
  <meta content="Browse through a database of NHL team stats since 1990. Practice building a scraper that handles common website interface components." name="description"/>
  <link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" rel="stylesheet"/>
  <link href="https://fonts.googleapis.com/css?family=Lato:400,700" rel="stylesheet" type="text/css"/>
  <link href="/static/css/styles.css" rel="stylesheet" type="text/css"/>
  <meta content="noindex" name="robots"/>
 </head>
 <body>
  <nav id="site-nav">
   <div class="container">
    <div class="col-md-12">
     <ul class="nav nav-tabs">
      <li id="nav-homepage">
       <a class="nav-link hidden-sm hidden-xs" href="/">
        <img id="nav-logo" src="/static/images/scraper-icon.png"/>
        Scrape This Site
       </a>
      </li>
      <li id="nav-sandbox">
       <a class="nav-link" href="/pages/">
        <i class="glyphicon glyphicon-console hidden-sm hidden-xs">
        </i>
        Sandbox
       </a>
      </li>
      <li id="nav-lessons">
       <a class="nav-link" href="/lessons/">
        <i class="glyphicon glyphicon-education hidden-sm hidden-xs">
        </i>
        Lessons
       </a>
      </li>
      <li id="nav-faq">
       <a class="nav-link" href="/faq/">
        <i class="glyphicon glyphicon-flag hidden-sm hidden-xs">
        </i>
        FAQ
       </a>
      </li>
      <li class="pull-right" id="nav-login">
       <a class="nav-link" href="/login/">
        Login
       </a>
      </li>
     </ul>
    </div>
   </div>
  </nav>
  <script type="text/javascript">
   var path = document.location.pathname;
            var tab = undefined;
            if (path === "/"){
                tab = document.querySelector("#nav-homepage");
            } else if (path.indexOf("/faq/") === 0){
                tab = document.querySelector("#nav-faq");
            } else if (path.indexOf("/lessons/") === 0){
                tab = document.querySelector("#nav-lessons");
            } else if (path.indexOf("/pages/") === 0) {
                tab = document.querySelector("#nav-sandbox");
            } else if (path.indexOf("/login/") === 0) {
                tab = document.querySelector("#nav-login");
            }
            tab.classList.add("active")
  </script>
  <div id="page">
   <section id="hockey">
    <div class="container">
     <div class="row">
      <div class="col-md-12">
       <h1>
        Hockey Teams: Forms, Searching and Pagination
        <small>
         25 items
        </small>
       </h1>
       <hr/>
      </div>
     </div>
     <div class="row">
      <div class="col-md-12">
       <p class="lead">
        Browse through a database of NHL team stats since 1990. Practice building a scraper that handles common website interface components.
                            Take a look at how pagination and search elements change the URL as your browse. Build a web scraper that can conduct searches and paginate through the results.
       </p>
       <hr/>
      </div>
     </div>
     <div class="row">
      <div class="col-md-6">
       <p>
        <i class="glyphicon glyphicon-education">
        </i>
        There are
        <a href="/lessons/">
         8 video lessons
        </a>
        that show you how to scrape this page.
       </p>
       <hr/>
      </div>
      <div class="col-md-6 text-right">
       <p>
        Data via
        <a class="data-attribution" href="http://www.opensourcesports.com/hockey/" target="_blank">
         http://www.opensourcesports.com/hockey/
        </a>
       </p>
       <hr/>
      </div>
     </div>
     <div class="row search-area">
      <div class="col-md-12 text-center">
       <form action="/pages/forms/" class="form form-inline" method="GET">
        <label for="q">
         Search for Teams:
        </label>
        <input class="form-control" id="q" name="q" placeholder="Search for Teams" type="text"/>
        <input class="btn btn-primary" type="submit" value="Search"/>
       </form>
       <hr/>
      </div>
     </div>
     <!--.row.search-area-->
     <table class="table">
      <tr>
       <th>
        Team Name
       </th>
       <th>
        Year
       </th>
       <th>
        Wins
       </th>
       <th>
        Losses
       </th>
       <th>
        OT Losses
       </th>
       <th>
        Win %
       </th>
       <th>
        Goals For (GF)
       </th>
       <th>
        Goals Against (GA)
       </th>
       <th>
        + / -
       </th>
      </tr>
      <tr class="team">
       <td class="name">
        Boston Bruins
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        44
       </td>
       <td class="losses">
        24
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-success">
        0.55
       </td>
       <td class="gf">
        299
       </td>
       <td class="ga">
        264
       </td>
       <td class="diff text-success">
        35
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Buffalo Sabres
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        31
       </td>
       <td class="losses">
        30
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.388
       </td>
       <td class="gf">
        292
       </td>
       <td class="ga">
        278
       </td>
       <td class="diff text-success">
        14
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Calgary Flames
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        46
       </td>
       <td class="losses">
        26
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-success">
        0.575
       </td>
       <td class="gf">
        344
       </td>
       <td class="ga">
        263
       </td>
       <td class="diff text-success">
        81
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Chicago Blackhawks
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        49
       </td>
       <td class="losses">
        23
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-success">
        0.613
       </td>
       <td class="gf">
        284
       </td>
       <td class="ga">
        211
       </td>
       <td class="diff text-success">
        73
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Detroit Red Wings
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        34
       </td>
       <td class="losses">
        38
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.425
       </td>
       <td class="gf">
        273
       </td>
       <td class="ga">
        298
       </td>
       <td class="diff text-danger">
        -25
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Edmonton Oilers
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        37
       </td>
       <td class="losses">
        37
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.463
       </td>
       <td class="gf">
        272
       </td>
       <td class="ga">
        272
       </td>
       <td class="diff text-success">
        0
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Hartford Whalers
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        31
       </td>
       <td class="losses">
        38
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.388
       </td>
       <td class="gf">
        238
       </td>
       <td class="ga">
        276
       </td>
       <td class="diff text-danger">
        -38
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Los Angeles Kings
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        46
       </td>
       <td class="losses">
        24
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-success">
        0.575
       </td>
       <td class="gf">
        340
       </td>
       <td class="ga">
        254
       </td>
       <td class="diff text-success">
        86
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Minnesota North Stars
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        27
       </td>
       <td class="losses">
        39
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.338
       </td>
       <td class="gf">
        256
       </td>
       <td class="ga">
        266
       </td>
       <td class="diff text-danger">
        -10
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Montreal Canadiens
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        39
       </td>
       <td class="losses">
        30
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.487
       </td>
       <td class="gf">
        273
       </td>
       <td class="ga">
        249
       </td>
       <td class="diff text-success">
        24
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        New Jersey Devils
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        32
       </td>
       <td class="losses">
        33
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.4
       </td>
       <td class="gf">
        272
       </td>
       <td class="ga">
        264
       </td>
       <td class="diff text-success">
        8
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        New York Islanders
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        25
       </td>
       <td class="losses">
        45
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.312
       </td>
       <td class="gf">
        223
       </td>
       <td class="ga">
        290
       </td>
       <td class="diff text-danger">
        -67
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        New York Rangers
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        36
       </td>
       <td class="losses">
        31
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.45
       </td>
       <td class="gf">
        297
       </td>
       <td class="ga">
        265
       </td>
       <td class="diff text-success">
        32
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Philadelphia Flyers
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        33
       </td>
       <td class="losses">
        37
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.412
       </td>
       <td class="gf">
        252
       </td>
       <td class="ga">
        267
       </td>
       <td class="diff text-danger">
        -15
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Pittsburgh Penguins
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        41
       </td>
       <td class="losses">
        33
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-success">
        0.512
       </td>
       <td class="gf">
        342
       </td>
       <td class="ga">
        305
       </td>
       <td class="diff text-success">
        37
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Quebec Nordiques
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        16
       </td>
       <td class="losses">
        50
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.2
       </td>
       <td class="gf">
        236
       </td>
       <td class="ga">
        354
       </td>
       <td class="diff text-danger">
        -118
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        St. Louis Blues
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        47
       </td>
       <td class="losses">
        22
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-success">
        0.588
       </td>
       <td class="gf">
        310
       </td>
       <td class="ga">
        250
       </td>
       <td class="diff text-success">
        60
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Toronto Maple Leafs
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        23
       </td>
       <td class="losses">
        46
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.287
       </td>
       <td class="gf">
        241
       </td>
       <td class="ga">
        318
       </td>
       <td class="diff text-danger">
        -77
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Vancouver Canucks
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        28
       </td>
       <td class="losses">
        43
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.35
       </td>
       <td class="gf">
        243
       </td>
       <td class="ga">
        315
       </td>
       <td class="diff text-danger">
        -72
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Washington Capitals
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        37
       </td>
       <td class="losses">
        36
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.463
       </td>
       <td class="gf">
        258
       </td>
       <td class="ga">
        258
       </td>
       <td class="diff text-success">
        0
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Winnipeg Jets
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        26
       </td>
       <td class="losses">
        43
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.325
       </td>
       <td class="gf">
        260
       </td>
       <td class="ga">
        288
       </td>
       <td class="diff text-danger">
        -28
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Boston Bruins
       </td>
       <td class="year">
        1991
       </td>
       <td class="wins">
        36
       </td>
       <td class="losses">
        32
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.45
       </td>
       <td class="gf">
        270
       </td>
       <td class="ga">
        275
       </td>
       <td class="diff text-danger">
        -5
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Buffalo Sabres
       </td>
       <td class="year">
        1991
       </td>
       <td class="wins">
        31
       </td>
       <td class="losses">
        37
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.388
       </td>
       <td class="gf">
        289
       </td>
       <td class="ga">
        299
       </td>
       <td class="diff text-danger">
        -10
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Calgary Flames
       </td>
       <td class="year">
        1991
       </td>
       <td class="wins">
        31
       </td>
       <td class="losses">
        37
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.388
       </td>
       <td class="gf">
        296
       </td>
       <td class="ga">
        305
       </td>
       <td class="diff text-danger">
        -9
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Chicago Blackhawks
       </td>
       <td class="year">
        1991
       </td>
       <td class="wins">
        36
       </td>
       <td class="losses">
        29
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.45
       </td>
       <td class="gf">
        257
       </td>
       <td class="ga">
        236
       </td>
       <td class="diff text-success">
        21
       </td>
      </tr>
     </table>
     <div class="row pagination-area">
      <div class="col-md-10 text-center">
       <ul class="pagination">
        <li>
         <a href="/pages/forms/?page_num=1">
          1
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=2">
          2
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=3">
          3
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=4">
          4
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=5">
          5
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=6">
          6
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=7">
          7
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=8">
          8
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=9">
          9
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=10">
          10
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=11">
          11
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=12">
          12
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=13">
          13
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=14">
          14
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=15">
          15
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=16">
          16
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=17">
          17
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=18">
          18
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=19">
          19
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=20">
          20
         </a>

In [7]:
title = soup.title
print(title.text)

Hockey Teams: Forms, Searching and Pagination | Scrape This Site | A public sandbox for learning web scraping

In [8]:
first_paragraph = soup.find("a")
print(first_paragraph.text)

                                Scrape This Site

In [10]:
teams = soup.find_all("tr", class_="team")

for team in teams:
    cols = team.find_all("td")
    
    name = cols[0].text.strip()   # Team name
    wins = cols[2].text.strip()   # Wins column
    
    print(f"{name} - {wins}")

Boston Bruins - 44
Buffalo Sabres - 31
Calgary Flames - 46
Chicago Blackhawks - 49
Detroit Red Wings - 34
Edmonton Oilers - 37
Hartford Whalers - 31
Los Angeles Kings - 46
Minnesota North Stars - 27
Montreal Canadiens - 39
New Jersey Devils - 32
New York Islanders - 25
New York Rangers - 36
Philadelphia Flyers - 33
Pittsburgh Penguins - 41
Quebec Nordiques - 16
St. Louis Blues - 47
Toronto Maple Leafs - 23
Vancouver Canucks - 28
Washington Capitals - 37
Winnipeg Jets - 26
Boston Bruins - 36
Buffalo Sabres - 31
Calgary Flames - 31
Chicago Blackhawks - 36

In [ ]:
Webscraping using def

In [38]:
def scrape_quotes():
    import requests
    from bs4 import BeautifulSoup

    url = "http://quotes.toscrape.com"
    response = requests.get(url)

    soup = BeautifulSoup(response.text, "html.parser")

    quotes = soup.find_all("span", class_="text")
    authors = soup.find_all("small", class_="author")

    for quote, author in zip(quotes, authors):
        print(f"{quote.text.strip()} - {author.text.strip()}")


# calling the function
scrape_quotes()

“The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.” - Albert Einstein
“It is our choices, Harry, that show what we truly are, far more than our abilities.” - J.K. Rowling
“There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.” - Albert Einstein
“The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.” - Jane Austen
“Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.” - Marilyn Monroe
“Try not to become a man of success. Rather become a man of value.” - Albert Einstein
“It is better to be hated for what you are than to be loved for what you are not.” - André Gide
“I have not failed. I've just found 10,000 ways that won't work.” - Thomas A. Edison
“A woman is like a tea bag; you never know how strong it is until it's in hot water.” - Eleanor Roosevelt
“A day without sunshine is like, you know, night.” - Steve Martin

Webscraping using headers

In [13]:
import requests
from bs4 import BeautifulSoup

url = "http://books.toscrape.com/"

headers = {
    "User-Agent": "Mozilla/5.0"
}

response = requests.get(url, headers=headers)

soup = BeautifulSoup(response.text, "html.parser")

book_names = soup.find_all("h3")
prices = soup.find_all("p", class_="price_color")

for name, price in zip(book_names, prices):
    book_title = name.find("a").get("title")
    print(f"{book_title} - {price.text.strip()}")

A Light in the Attic - Â£51.77
Tipping the Velvet - Â£53.74
Soumission - Â£50.10
Sharp Objects - Â£47.82
Sapiens: A Brief History of Humankind - Â£54.23
The Requiem Red - Â£22.65
The Dirty Little Secrets of Getting Your Dream Job - Â£33.34
The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull - Â£17.93
The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics - Â£22.60
The Black Maria - Â£52.15
Starving Hearts (Triangular Trade Trilogy, #1) - Â£13.99
Shakespeare's Sonnets - Â£20.66
Set Me Free - Â£17.46
Scott Pilgrim's Precious Little Life (Scott Pilgrim #1) - Â£52.29
Rip it Up and Start Again - Â£35.02
Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991 - Â£57.25
Olio - Â£23.88
Mesaerion: The Best Science Fiction Stories 1800-1849 - Â£37.59
Libertarianism for Beginners - Â£51.33
It's Only the Himalayas - Â£45.17

Web Scraping Using Enumerate

In [14]:
import requests
from bs4 import BeautifulSoup

url = "https://www.scrapethissite.com/pages/simple/"

headers = {
    "User-Agent": "Mozilla/5.0"
}

response = requests.get(url, headers=headers)
soup = BeautifulSoup(response.text, "html.parser")

countries = soup.find_all("h3", class_="country-name")
capitals = soup.find_all("span", class_="country-capital")

for i, (country, capital) in enumerate(zip(countries, capitals), start=1):
    country_name = country.text.strip()
    capital_name = capital.text.strip()
    
    print(f"{i}. {country_name} - {capital_name}")

1. Andorra - Andorra la Vella
2. United Arab Emirates - Abu Dhabi
3. Afghanistan - Kabul
4. Antigua and Barbuda - St. John's
5. Anguilla - The Valley
6. Albania - Tirana
7. Armenia - Yerevan
8. Angola - Luanda
9. Antarctica - None
10. Argentina - Buenos Aires
11. American Samoa - Pago Pago
12. Austria - Vienna
13. Australia - Canberra
14. Aruba - Oranjestad
15. Åland - Mariehamn
16. Azerbaijan - Baku
17. Bosnia and Herzegovina - Sarajevo
18. Barbados - Bridgetown
19. Bangladesh - Dhaka
20. Belgium - Brussels
21. Burkina Faso - Ouagadougou
22. Bulgaria - Sofia
23. Bahrain - Manama
24. Burundi - Bujumbura
25. Benin - Porto-Novo
26. Saint Barthélemy - Gustavia
27. Bermuda - Hamilton
28. Brunei - Bandar Seri Begawan
29. Bolivia - Sucre
30. Bonaire - Kralendijk
31. Brazil - Brasília
32. Bahamas - Nassau
33. Bhutan - Thimphu
34. Bouvet Island - None
35. Botswana - Gaborone
36. Belarus - Minsk
37. Belize - Belmopan
38. Canada - Ottawa
39. Cocos [Keeling] Islands - West Island
40. Democratic Republic of the Congo - Kinshasa
41. Central African Republic - Bangui
42. Republic of the Congo - Brazzaville
43. Switzerland - Bern
44. Ivory Coast - Yamoussoukro
45. Cook Islands - Avarua
46. Chile - Santiago
47. Cameroon - Yaoundé
48. China - Beijing
49. Colombia - Bogotá
50. Costa Rica - San José
51. Cuba - Havana
52. Cape Verde - Praia
53. Curacao - Willemstad
54. Christmas Island - Flying Fish Cove
55. Cyprus - Nicosia
56. Czech Republic - Prague
57. Germany - Berlin
58. Djibouti - Djibouti
59. Denmark - Copenhagen
60. Dominica - Roseau
61. Dominican Republic - Santo Domingo
62. Algeria - Algiers
63. Ecuador - Quito
64. Estonia - Tallinn
65. Egypt - Cairo
66. Western Sahara - Laâyoune / El Aaiún
67. Eritrea - Asmara
68. Spain - Madrid
69. Ethiopia - Addis Ababa
70. Finland - Helsinki
71. Fiji - Suva
72. Falkland Islands - Stanley
73. Micronesia - Palikir
74. Faroe Islands - Tórshavn
75. France - Paris
76. Gabon - Libreville
77. United Kingdom - London
78. Grenada - St. George's
79. Georgia - Tbilisi
80. French Guiana - Cayenne
81. Guernsey - St Peter Port
82. Ghana - Accra
83. Gibraltar - Gibraltar
84. Greenland - Nuuk
85. Gambia - Bathurst
86. Guinea - Conakry
87. Guadeloupe - Basse-Terre
88. Equatorial Guinea - Malabo
89. Greece - Athens
90. South Georgia and the South Sandwich Islands - Grytviken
91. Guatemala - Guatemala City
92. Guam - Hagåtña
93. Guinea-Bissau - Bissau
94. Guyana - Georgetown
95. Hong Kong - Hong Kong
96. Heard Island and McDonald Islands - None
97. Honduras - Tegucigalpa
98. Croatia - Zagreb
99. Haiti - Port-au-Prince
100. Hungary - Budapest
101. Indonesia - Jakarta
102. Ireland - Dublin
103. Israel - None
104. Isle of Man - Douglas
105. India - New Delhi
106. British Indian Ocean Territory - None
107. Iraq - Baghdad
108. Iran - Tehran
109. Iceland - Reykjavik
110. Italy - Rome
111. Jersey - Saint Helier
112. Jamaica - Kingston
113. Jordan - Amman
114. Japan - Tokyo
115. Kenya - Nairobi
116. Kyrgyzstan - Bishkek
117. Cambodia - Phnom Penh
118. Kiribati - Tarawa
119. Comoros - Moroni
120. Saint Kitts and Nevis - Basseterre
121. North Korea - Pyongyang
122. South Korea - Seoul
123. Kuwait - Kuwait City
124. Cayman Islands - George Town
125. Kazakhstan - Astana
126. Laos - Vientiane
127. Lebanon - Beirut
128. Saint Lucia - Castries
129. Liechtenstein - Vaduz
130. Sri Lanka - Colombo
131. Liberia - Monrovia
132. Lesotho - Maseru
133. Lithuania - Vilnius
134. Luxembourg - Luxembourg
135. Latvia - Riga
136. Libya - Tripoli
137. Morocco - Rabat
138. Monaco - Monaco
139. Moldova - Chişinău
140. Montenegro - Podgorica
141. Saint Martin - Marigot
142. Madagascar - Antananarivo
143. Marshall Islands - Majuro
144. Macedonia - Skopje
145. Mali - Bamako
146. Myanmar [Burma] - Naypyitaw
147. Mongolia - Ulan Bator
148. Macao - Macao
149. Northern Mariana Islands - Saipan
150. Martinique - Fort-de-France
151. Mauritania - Nouakchott
152. Montserrat - Plymouth
153. Malta - Valletta
154. Mauritius - Port Louis
155. Maldives - Malé
156. Malawi - Lilongwe
157. Mexico - Mexico City
158. Malaysia - Kuala Lumpur
159. Mozambique - Maputo
160. Namibia - Windhoek
161. New Caledonia - Noumea
162. Niger - Niamey
163. Norfolk Island - Kingston
164. Nigeria - Abuja
165. Nicaragua - Managua
166. Netherlands - Amsterdam
167. Norway - Oslo
168. Nepal - Kathmandu
169. Nauru - Yaren
170. Niue - Alofi
171. New Zealand - Wellington
172. Oman - Muscat
173. Panama - Panama City
174. Peru - Lima
175. French Polynesia - Papeete
176. Papua New Guinea - Port Moresby
177. Philippines - Manila
178. Pakistan - Islamabad
179. Poland - Warsaw
180. Saint Pierre and Miquelon - Saint-Pierre
181. Pitcairn Islands - Adamstown
182. Puerto Rico - San Juan
183. Palestine - None
184. Portugal - Lisbon
185. Palau - Melekeok
186. Paraguay - Asunción
187. Qatar - Doha
188. Réunion - Saint-Denis
189. Romania - Bucharest
190. Serbia - Belgrade
191. Russia - Moscow
192. Rwanda - Kigali
193. Saudi Arabia - Riyadh
194. Solomon Islands - Honiara
195. Seychelles - Victoria
196. Sudan - Khartoum
197. Sweden - Stockholm
198. Singapore - Singapore
199. Saint Helena - Jamestown
200. Slovenia - Ljubljana
201. Svalbard and Jan Mayen - Longyearbyen
202. Slovakia - Bratislava
203. Sierra Leone - Freetown
204. San Marino - San Marino
205. Senegal - Dakar
206. Somalia - Mogadishu
207. Suriname - Paramaribo
208. South Sudan - Juba
209. São Tomé and Príncipe - São Tomé
210. El Salvador - San Salvador
211. Sint Maarten - Philipsburg
212. Syria - Damascus
213. Swaziland - Mbabane
214. Turks and Caicos Islands - Cockburn Town
215. Chad - N'Djamena
216. French Southern Territories - Port-aux-Français
217. Togo - Lomé
218. Thailand - Bangkok
219. Tajikistan - Dushanbe
220. Tokelau - None
221. East Timor - Dili
222. Turkmenistan - Ashgabat
223. Tunisia - Tunis
224. Tonga - Nuku'alofa
225. Turkey - Ankara
226. Trinidad and Tobago - Port of Spain
227. Tuvalu - Funafuti
228. Taiwan - Taipei
229. Tanzania - Dodoma
230. Ukraine - Kiev
231. Uganda - Kampala
232. U.S. Minor Outlying Islands - None
233. United States - Washington
234. Uruguay - Montevideo
235. Uzbekistan - Tashkent
236. Vatican City - Vatican City
237. Saint Vincent and the Grenadines - Kingstown
238. Venezuela - Caracas
239. British Virgin Islands - Road Town
240. U.S. Virgin Islands - Charlotte Amalie
241. Vietnam - Hanoi
242. Vanuatu - Port Vila
243. Wallis and Futuna - Mata-Utu
244. Samoa - Apia
245. Kosovo - Pristina
246. Yemen - Sanaa
247. Mayotte - Mamoudzou
248. South Africa - Pretoria
249. Zambia - Lusaka
250. Zimbabwe - Harare

Webscraping with Table Operactions

In [37]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
url = "https://en.wikipedia.org/wiki/List_of_countries_and_dependencies_by_population"
headers = {"User-Agent":"Mozilla/5.0"} #avoid blocking
response=requests.get(url,headers=headers)
soup = BeautifulSoup(response.text,"html.parser")
print(soup)

<!DOCTYPE html>

<html class="client-nojs vector-feature-language-in-header-enabled vector-feature-language-in-main-menu-disabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 skin-theme-clientpref-day vector-sticky-header-enabled wp25eastereggs-enable-clientpref-1 vector-toc-available skin-theme-clientpref-thumb-standard" dir="ltr" lang="en">
<head>
<meta charset="utf-8"/>
<title>List of countries and dependencies by population - Wikipedia</title>
<script>(function(){var className="client-js vector-feature-language-in-header-enabled vector-feature-language-in-main-menu-disabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 skin-theme-clientpref-day vector-sticky-header-enabled wp25eastereggs-enable-clientpref-1 vector-toc-available skin-theme-clientpref-thumb-standard";var cookie=document.cookie.match(/(?:^|; )enwikimwclientpreferences=([^;]+)/);if(cookie){cookie[1].split('%2C').forEach(function(pref){className=className.replace(new RegExp('(^| )'+pref.replace(/-clientpref-\w+$|[^\w-]+/g,'')+'-clientpref-\\w+( |$)'),'$1'+pref+'$2');});}document.documentElement.className=className;}());RLCONF={"wgBreakFrames":false,"wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgRequestId":"486a9c1d-28fd-4a4a-bd34-711ac811de89","wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"List_of_countries_and_dependencies_by_population","wgTitle":"List of countries and dependencies by population","wgCurRevisionId":1346918434,"wgRevisionId":1346918434,"wgArticleId":69058,"wgIsArticle":true,"wgIsRedirect":false,"wgAction":"view","wgUserName":null,"wgUserGroups":["*"],"wgCategories":["Pages with non-numeric formatnum arguments","CS1 Indonesian-language sources (id)","CS1 Russian-language sources (ru)","CS1 Thai-language sources (th)","CS1 Italian-language sources (it)","CS1 French-language sources (fr)","CS1 Portuguese-language sources (pt)","CS1 German-language sources (de)","CS1 Bulgarian-language sources (bg)","CS1 Spanish-language sources (es)","CS1 maint: url-status","CS1 Bosnian-language sources (bs)","CS1 Albanian-language sources (sq)","CS1 Romanian-language sources (ro)","Articles with short description","Short description is different from Wikidata","Wikipedia indefinitely semi-protected pages","Use dmy dates from March 2022","Use British English from August 2022","All Wikipedia articles written in British English","Lists of countries by population"],"wgPageViewLanguage":"en","wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgRelevantPageName":"List_of_countries_and_dependencies_by_population","wgRelevantArticleId":69058,"wgTempUserName":null,"wgIsProbablyEditable":false,"wgRelevantPageIsProbablyEditable":false,"wgRestrictionEdit":["autoconfirmed"],"wgRestrictionMove":["autoconfirmed"],"wgNoticeProject":"wikipedia","wgFlaggedRevsParams":{"tags":{"status":{"levels":1}}},"wgConfirmEditCaptchaNeededForGenericEdit":"hcaptcha","wgConfirmEditHCaptchaVisualEditorOnLoadIntegrationEnabled":false,"wgConfirmEditHCaptchaSiteKey":"5d0c670e-a5f4-4258-ad16-1f42792c9c62","wgMediaViewerOnClick":true,"wgMediaViewerEnabledByDefault":true,"wgPopupsFlags":0,"wgVisualEditor":{"pageLanguageCode":"en","pageLanguageDir":"ltr","pageVariantFallbacks":"en"},"wgMFDisplayWikibaseDescriptions":{"search":true,"watchlist":true,"tagline":false,"nearby":true},"wgWMESchemaEditAttemptStepOversample":false,"wgWMEPageLength":100000,"wgEditSubmitButtonLabelPublish":true,"wgVisualEditorPageIsDisambiguation":false,"wgULSPosition":"interlanguage","wgULSisCompactLinksEnabled":false,"wgVector2022LanguageInHeader":true,"wgULSisLanguageSelectorEmpty":false,"wgWikibaseItemId":"Q712280","wgCheckUserClientHintsHeadersJsApi":["brands","architecture","bitness","fullVersionList","mobile","model","platform","platformVersion"],"GEHomepageSuggestedEditsEnableTopics":true,"wgGESuggestedEditsTaskTypes":{"taskTypes":["copyedit","link-recommendation"],"unavailableTaskTypes":[]},"wgGETopicsMatchModeEnabled":false,"wgGELevelingUpEnabledForUser":false,"wgTestKitchenUserExperiments":{"overrides":[],"enrolled":[],"assigned":[],"subject_ids":[]}};
RLSTATE={"ext.globalCssJs.user.styles":"ready","site.styles":"ready","user.styles":"ready","ext.globalCssJs.user":"ready","user":"ready","user.options":"loading","ext.wikimediamessages.styles":"ready","ext.cite.styles":"ready","skins.vector.search.codex.styles":"ready","skins.vector.styles":"ready","skins.vector.icons":"ready","jquery.tablesorter.styles":"ready","jquery.makeCollapsible.styles":"ready","ext.visualEditor.desktopArticleTarget.noscript":"ready","ext.uls.interlanguage":"ready","wikibase.client.init":"ready","ext.wp25EasterEggs.styles":"ready"};RLPAGEMODULES=["ext.parsermigration.survey","ext.cite.ux-enhancements","mediawiki.page.media","site","mediawiki.page.ready","jquery.tablesorter","jquery.makeCollapsible","mediawiki.toc","skins.vector.js","ext.centralNotice.geoIP","ext.centralNotice.startUp","ext.gadget.ReferenceTooltips","ext.gadget.switcher","ext.urlShortener.toolbar","ext.centralauth.centralautologin","mmv.bootstrap","ext.popups","ext.visualEditor.desktopArticleTarget.init","ext.echo.centralauth","ext.eventLogging","ext.wikimediaEvents","ext.navigationTiming","ext.uls.interface","ext.cx.eventlogging.campaigns","ext.cx.uls.quick.actions","wikibase.client.vector-2022","wikibase.databox.fromWikidata","ext.checkUser.clientHints","ext.quicksurveys.init","ext.growthExperiments.SuggestedEditSession","ext.testKitchen","ext.wp25EasterEggs"];</script>
<script>(RLQ=window.RLQ||[]).push(function(){mw.loader.impl(function(){return["user.options@12s5i",function($,jQuery,require,module){mw.user.tokens.set({"patrolToken":"+\\","watchToken":"+\\","csrfToken":"+\\"});
}];});});</script>
<link href="/w/load.php?lang=en&amp;modules=ext.cite.styles%7Cext.uls.interlanguage%7Cext.visualEditor.desktopArticleTarget.noscript%7Cext.wikimediamessages.styles%7Cext.wp25EasterEggs.styles%7Cjquery.makeCollapsible.styles%7Cjquery.tablesorter.styles%7Cskins.vector.icons%2Cstyles%7Cskins.vector.search.codex.styles%7Cwikibase.client.init&amp;only=styles&amp;skin=vector-2022" rel="stylesheet"/>
<script async="" src="/w/load.php?lang=en&amp;modules=startup&amp;only=scripts&amp;raw=1&amp;skin=vector-2022"></script>
<meta content="" name="ResourceLoaderDynamicStyles"/>
<link href="/w/load.php?lang=en&amp;modules=site.styles&amp;only=styles&amp;skin=vector-2022" rel="stylesheet"/>
<meta content="MediaWiki 1.46.0-wmf.22" name="generator"/>
<meta content="origin" name="referrer"/>
<meta content="origin-when-cross-origin" name="referrer"/>
<meta content="max-image-preview:standard" name="robots"/>
<meta content="telephone=no" name="format-detection"/>
<meta content="https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Global_population_cartogram.png/1280px-Global_population_cartogram.png" property="og:image"/>
<meta content="1200" property="og:image:width"/>
<meta content="459" property="og:image:height"/>
<meta content="width=1120" name="viewport"/>
<meta content="List of countries and dependencies by population - Wikipedia" property="og:title"/>
<meta content="website" property="og:type"/>
<link href="//upload.wikimedia.org" rel="preconnect"/>
<link href="/static/apple-touch/wikipedia.png" rel="apple-touch-icon"/>
<link href="/static/favicon/wikipedia.ico" rel="icon"/>
<link href="/w/rest.php/v1/search" rel="search" title="Wikipedia (en)" type="application/opensearchdescription+xml"/>
<link href="//en.wikipedia.org/w/api.php?action=rsd" rel="EditURI" type="application/rsd+xml"/>
<link href="https://en.wikipedia.org/wiki/List_of_countries_and_dependencies_by_population" rel="canonical"/>
<link href="https://creativecommons.org/licenses/by-sa/4.0/deed.en" rel="license"/>
<link href="/w/index.php?title=Special:RecentChanges&amp;feed=atom" rel="alternate" title="Wikipedia Atom feed" type="application/atom+xml"/>
<link href="//meta.wikimedia.org" rel="dns-prefetch">
<link href="auth.wikimedia.org" rel="dns-prefetch"/>
</link></head>
<body class="skin--responsive skin-vector skin-vector-search-vue mediawiki ltr sitedir-ltr mw-hide-empty-elt ns-0 ns-subject page-List_of_countries_and_dependencies_by_population rootpage-List_of_countries_and_dependencies_by_population skin-vector-2022 action-view">
<div aria-live="polite" class="mw-aria-live-region" id="mw-aria-live-region"></div><a class="mw-jump-link" href="#bodyContent">Jump to content</a>
<div class="vector-header-container">
<header class="vector-header mw-header no-font-mode-scale">
<div class="vector-header-start">
<nav aria-label="Site" class="vector-main-menu-landmark">
<div class="vector-dropdown vector-main-menu-dropdown vector-button-flush-left vector-button-flush-right" id="vector-main-menu-dropdown" title="Main menu">
<input aria-haspopup="true" aria-label="Main menu" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-main-menu-dropdown" id="vector-main-menu-dropdown-checkbox" role="button" type="checkbox"/>
<label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-main-menu-dropdown-checkbox" id="vector-main-menu-dropdown-label"><span class="vector-icon mw-ui-icon-menu mw-ui-icon-wikimedia-menu"></span>
<span class="vector-dropdown-label-text">Main menu</span>
</label>
<div class="vector-dropdown-content">
<div class="vector-unpinned-container" id="vector-main-menu-unpinned-container">
<div class="vector-main-menu vector-pinnable-element" id="vector-main-menu">
<div class="vector-pinnable-header vector-main-menu-pinnable-header vector-pinnable-header-unpinned" data-feature-name="main-menu-pinned" data-pinnable-element-id="vector-main-menu" data-pinned-container-id="vector-main-menu-pinned-container" data-unpinned-container-id="vector-main-menu-unpinned-container">
<div class="vector-pinnable-header-label">Main menu</div>
<button class="vector-pinnable-header-toggle-button vector-pinnable-header-pin-button" data-event-name="pinnable-header.vector-main-menu.pin">move to sidebar</button>
<button class="vector-pinnable-header-toggle-button vector-pinnable-header-unpin-button" data-event-name="pinnable-header.vector-main-menu.unpin">hide</button>
</div>
<div class="vector-menu mw-portlet mw-portlet-navigation" id="p-navigation">
<div class="vector-menu-heading">
		Navigation
	</div>
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="mw-list-item" id="n-mainpage-description"><a accesskey="z" href="/wiki/Main_Page" title="Visit the main page [z]"><span>Main page</span></a></li><li class="mw-list-item" id="n-contents"><a href="/wiki/Wikipedia:Contents" title="Guides to browsing Wikipedia"><span>Contents</span></a></li><li class="mw-list-item" id="n-currentevents"><a href="/wiki/Portal:Current_events" title="Articles related to current events"><span>Current events</span></a></li><li class="mw-list-item" id="n-randompage"><a accesskey="x" href="/wiki/Special:Random" title="Visit a randomly selected article [x]"><span>Random article</span></a></li><li class="mw-list-item" id="n-aboutsite"><a href="/wiki/Wikipedia:About" title="Learn about Wikipedia and how it works"><span>About Wikipedia</span></a></li><li class="mw-list-item" id="n-contactpage"><a href="//en.wikipedia.org/wiki/Wikipedia:Contact_us" title="How to contact Wikipedia"><span>Contact us</span></a></li>
</ul>
</div>
</div>
<div class="vector-menu mw-portlet mw-portlet-interaction" id="p-interaction">
<div class="vector-menu-heading">
		Contribute
	</div>
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="mw-list-item" id="n-help"><a href="/wiki/Help:Contents" title="Guidance on how to use and edit Wikipedia"><span>Help</span></a></li><li class="mw-list-item" id="n-introduction"><a href="/wiki/Help:Introduction" title="Learn how to edit Wikipedia"><span>Learn to edit</span></a></li><li class="mw-list-item" id="n-portal"><a href="/wiki/Wikipedia:Community_portal" title="The hub for editors"><span>Community portal</span></a></li><li class="mw-list-item" id="n-recentchanges"><a accesskey="r" href="/wiki/Special:RecentChanges" title="A list of recent changes to Wikipedia [r]"><span>Recent changes</span></a></li><li class="mw-list-item" id="n-upload"><a href="/wiki/Wikipedia:File_upload_wizard" title="Add images or other media for use on Wikipedia"><span>Upload file</span></a></li><li class="mw-list-item" id="n-specialpages"><a accesskey="q" href="/wiki/Special:SpecialPages" title="A list of all special pages [q]"><span>Special pages</span></a></li>
</ul>
</div>
</div>
</div>
</div>
</div>
</div>
</nav>
<a class="mw-logo" href="/wiki/Main_Page">
<img alt="" aria-hidden="true" class="mw-logo-icon" height="50" src="/static/images/icons/enwiki-25.svg" width="50"/>
<span class="mw-logo-container skin-invert">
<img alt="Wikipedia" class="mw-logo-wordmark" src="/static/images/mobile/copyright/wikipedia-wordmark-en-25.svg" style="width: 8.75em; height: 1.375em;"/>
<img alt="The Free Encyclopedia" class="mw-logo-tagline" height="11" src="/static/images/mobile/copyright/wikipedia-tagline-en-25.svg" style="width: 8.75em; height: 0.6875em;" width="140"/>
</span>
</a>
</div>
<div class="vector-header-end">
<div class="vector-search-box-vue vector-search-box-collapses vector-search-box-show-thumbnail vector-search-box-auto-expand-width vector-search-box" id="p-search" role="search">
<a accesskey="f" class="cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only search-toggle" href="/wiki/Special:Search" title="Search Wikipedia [f]"><span class="vector-icon mw-ui-icon-search mw-ui-icon-wikimedia-search"></span>
<span>Search</span>
</a>
<div class="vector-typeahead-search-container">
<div class="cdx-typeahead-search cdx-typeahead-search--show-thumbnail cdx-typeahead-search--auto-expand-width">
<form action="/w/index.php" class="cdx-search-input cdx-search-input--has-end-button" id="searchform">
<div class="cdx-search-input__input-wrapper" data-search-loc="header-moved" id="simpleSearch">
<div class="cdx-text-input cdx-text-input--has-start-icon">
<input accesskey="f" aria-label="Search Wikipedia" autocapitalize="none" autocomplete="off" class="cdx-text-input__input mw-searchInput" id="searchInput" name="search" placeholder="Search Wikipedia" spellcheck="false" title="Search Wikipedia [f]" type="search"/>
<span class="cdx-text-input__icon cdx-text-input__start-icon"></span>
</div>
<input name="title" type="hidden" value="Special:Search"/>
</div>
<button class="cdx-button cdx-search-input__end-button">Search</button>
</form>
</div>
</div>
</div>
<nav aria-label="Personal tools" class="vector-user-links vector-user-links-wide">
<div class="vector-user-links-main">
<div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-preferences">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
</ul>
</div>
</div>
<div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-userpage">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
</ul>
</div>
</div>
<nav aria-label="Appearance" class="vector-appearance-landmark">
<div class="vector-dropdown" id="vector-appearance-dropdown" title="Change the appearance of the page's font size, width, and color">
<input aria-haspopup="true" aria-label="Appearance" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-appearance-dropdown" id="vector-appearance-dropdown-checkbox" role="button" type="checkbox"/>
<label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-appearance-dropdown-checkbox" id="vector-appearance-dropdown-label"><span class="vector-icon mw-ui-icon-appearance mw-ui-icon-wikimedia-appearance"></span>
<span class="vector-dropdown-label-text">Appearance</span>
</label>
<div class="vector-dropdown-content">
<div class="vector-unpinned-container" id="vector-appearance-unpinned-container">
</div>
</div>
</div>
</nav>
<div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-notifications">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
</ul>
</div>
</div>
<div class="vector-menu mw-portlet" id="p-vector-user-menu-overflow">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="user-links-collapsible-item mw-list-item user-links-collapsible-item" id="pt-sitesupport-2"><a class="" data-mw-interface="" href="https://donate.wikimedia.org/?wmf_source=donate&amp;wmf_medium=sidebar&amp;wmf_campaign=en.wikipedia.org&amp;uselang=en"><span>Donate</span></a>
</li>
<li class="user-links-collapsible-item mw-list-item user-links-collapsible-item" id="pt-createaccount-2"><a class="" data-mw-interface="" href="/w/index.php?title=Special:CreateAccount&amp;returnto=List+of+countries+and+dependencies+by+population" title="You are encouraged to create an account and log in; however, it is not mandatory"><span>Create account</span></a>
</li>
<li class="user-links-collapsible-item mw-list-item user-links-collapsible-item" id="pt-login-2"><a accesskey="o" class="" data-mw-interface="" href="/w/index.php?title=Special:UserLogin&amp;returnto=List+of+countries+and+dependencies+by+population" title="You're encouraged to log in; however, it's not mandatory. [o]"><span>Log in</span></a>
</li>
</ul>
</div>
</div>
</div>
<div class="vector-dropdown vector-user-menu vector-button-flush-right vector-user-menu-logged-out user-links-collapsible-item" id="vector-user-links-dropdown" title="Log in and more options">
<input aria-haspopup="true" aria-label="Personal tools" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-user-links-dropdown" id="vector-user-links-dropdown-checkbox" role="button" type="checkbox"/>
<label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-user-links-dropdown-checkbox" id="vector-user-links-dropdown-label"><span class="vector-icon mw-ui-icon-ellipsis mw-ui-icon-wikimedia-ellipsis"></span>
<span class="vector-dropdown-label-text">Personal tools</span>
</label>
<div class="vector-dropdown-content">
<div class="vector-menu mw-portlet mw-portlet-personal user-links-collapsible-item" id="p-personal" title="User menu">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">

In [22]:
tables = soup.find_all("table",class_="wikitable")

In [23]:
if not tables:
    raise ValueError("No tables with class 'wikitable' found on the page")
table =tables[0]

In [24]:
rows=table.find_all("tr")

In [25]:
data =[]
for row in rows:
    cols=row.find_all(["td","th"])
    cols=[col.get_text(strip=True)for col in cols]
    data.append(cols)

df=pd.DataFrame(data)

print(df.head())

               0              1          2            3  \
0       Location     Population  % ofworld         Date
1          World  8,232,000,000       100%  13 Jun 2025
2          India  1,417,492,000      17.2%   1 Jul 2025
3          China  1,404,890,000      17.1%  31 Dec 2025
4  United States    341,784,857       4.1%   1 Jul 2025

                                            4      5
0  Source (official or fromtheUnited Nations)  Notes
1                         UN projection[1][3]
2                      Official projection[4]    [b]
3                        Official estimate[5]    [c]
4                        Official estimate[6]    [d]

In [26]:
df.columns = df.iloc[0]
df = df[1:]
df.columns = df.columns.str.strip()
df.head()

,Location,Population,% ofworld,Date,Source (official or fromtheUnited Nations),Notes
1,World,"8,232,000,000",100%,13 Jun 2025,UN projection[1][3],
2,India,"1,417,492,000",17.2%,1 Jul 2025,Official projection[4],[b]
3,China,"1,404,890,000",17.1%,31 Dec 2025,Official estimate[5],[c]
4,United States,"341,784,857",4.1%,1 Jul 2025,Official estimate[6],[d]
5,Indonesia,"288,315,089",3.5%,31 Dec 2025,National annual projection[7],

In [27]:
#selecting specific columns
df[["Location","% ofworld"]]

0                              Location % ofworld
1                                 World      100%
2                                 India     17.2%
3                                 China     17.1%
4                         United States      4.1%
5                             Indonesia      3.5%
..                                  ...       ...
236         Christmas Island(Australia)        0%
237                   Niue(New Zealand)        0%
238                        Vatican City        0%
239  Cocos (Keeling) Islands(Australia)        0%
240                Pitcairn Islands(UK)        0%

[240 rows x 2 columns]

In [28]:
#filtering rows
df[df["Location"]=="India"]

,Location,Population,% ofworld,Date,Source (official or fromtheUnited Nations),Notes
2,India,"1,417,492,000",17.2%,1 Jul 2025,Official projection[4],[b]

In [29]:
#sorting data
df.sort_values(by='Population', ascending=True)

,Location,Population,% ofworld,Date,Source (official or fromtheUnited Nations),Notes
161,Djibouti,"1,066,809",0.01%,20 May 2024,2024 census result[176],
160,Eswatini,"1,235,549",0.01%,1 Jul 2024,Official projection[175],
159,Mauritius,"1,241,856",0.02%,31 Dec 2025,National estimate[174],
158,Estonia,"1,362,954",0.02%,1 Jan 2026,Official estimate[173],
157,Trinidad and Tobago,"1,367,764",0.02%,30 Jun 2025,Official estimate[172],
...,...,...,...,...,...,...
96,Honduras,"9,892,632",0.1%,1 Jul 2024,National annual projection[106],
165,Fiji,"902,623",0.01%,1 Jan 2026,National annual projection[180],
164,Comoros,"944,388",0.01%,2026,Official estimate[179],
163,Guyana,"956,044",0.01%,31 Dec 2024,Official estimate[178],
162,Cyprus,"983,000",0.01%,31 Dec 2024,Official estimate[177],[ac]

In [30]:
# handle missing data
df.isnull()

,Location,Population,% ofworld,Date,Source (official or fromtheUnited Nations),Notes
1,False,False,False,False,False,False
2,False,False,False,False,False,False
3,False,False,False,False,False,False
4,False,False,False,False,False,False
5,False,False,False,False,False,False
...,...,...,...,...,...,...
236,False,False,False,False,False,False
237,False,False,False,False,False,False
238,False,False,False,False,False,False
239,False,False,False,False,False,False
240,False,False,False,False,False,False

In [31]:
df = df.dropna()

In [32]:
df['Population'] = pd.to_numeric(df['Population'].astype(str).str.replace(',', ''), errors='coerce')
df['% ofworld'] = pd.to_numeric(df['% ofworld'].astype(str).str.replace(',', ''), errors='coerce')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 240 entries, 1 to 240
Data columns (total 6 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Location                                    240 non-null    object
 1   Population                                  240 non-null    int64
 2   % ofworld                                   0 non-null      float64
 3   Date                                        240 non-null    object
 4   Source (official or fromtheUnited Nations)  240 non-null    object
 5   Notes                                       240 non-null    object
dtypes: float64(1), int64(1), object(4)
memory usage: 11.4+ KB

In [33]:
df['Population_in_millions'] = df['Population'] / 1_000_000
df.head()

,Location,Population,% ofworld,Date,Source (official or fromtheUnited Nations),Notes,Population_in_millions
1,World,8232000000,NaN,13 Jun 2025,UN projection[1][3],,8232.000000
2,India,1417492000,NaN,1 Jul 2025,Official projection[4],[b],1417.492000
3,China,1404890000,NaN,31 Dec 2025,Official estimate[5],[c],1404.890000
4,United States,341784857,NaN,1 Jul 2025,Official estimate[6],[d],341.784857
5,Indonesia,288315089,NaN,31 Dec 2025,National annual projection[7],,288.315089

In [34]:
df.to_csv("data.csv",index=False)

In [36]:
for index, row in df.iterrows():
   print(row['Location'],"-", row['Population_in_millions'])

World - 8232.0
India - 1417.492
China - 1404.89
United States - 341.784857
Indonesia - 288.315089
Pakistan - 241.499431
Nigeria - 223.8
Brazil - 213.421037
Bangladesh - 169.828911
Russia - 146.028325
Mexico - 131.001723
Japan - 122.85
Philippines - 114.1236
Democratic Republic of the Congo - 112.832
Ethiopia - 111.652998
Egypt - 107.868296
Vietnam - 102.3
Iran - 86.563
Turkey - 86.092168
Germany - 83.497147
United Kingdom - 69.487
France - 69.081996
Tanzania - 68.153004
Thailand - 65.826149
South Africa - 63.100945
Italy - 58.942828
Kenya - 53.330978
Colombia - 53.057212
Sudan - 51.662
Myanmar - 51.375327
South Korea - 51.111158
Spain - 49.570725
Algeria - 47.4
Argentina - 46.387098
Iraq - 46.118793
Uganda - 45.905417
Afghanistan - 43.844
Canada - 41.472081
Uzbekistan - 38.236704
Poland - 37.314
Morocco - 36.82833
Angola - 36.604681
Saudi Arabia - 35.30028
Peru - 34.350244
Malaysia - 34.3344
Mozambique - 34.090466
Ghana - 33.74238
Yemen - 32.684503
Madagascar - 31.727042
Ivory Coast - 31.719275
Nepal - 29.91184
Cameroon - 29.442327
Ukraine - 28.7
Venezuela - 28.517
Australia - 27.724744
Niger - 27.52275
North Korea - 25.95
Syria - 25.620427
Burkina Faso - 24.070553
Taiwan - 23.280273
Mali - 22.395489
Sri Lanka - 21.7818
Malawi - 20.734262
Kazakhstan - 20.53224
Chile - 20.206953
Zambia - 19.693423
Somalia - 19.655
Chad - 19.340757
Romania - 19.036031
Senegal - 18.593258
Netherlands - 18.137265
Ecuador - 18.10366
Guatemala - 18.07981
Cambodia - 17.57776
Zimbabwe - 17.073087
South Sudan - 15.786898
Guinea - 17.521167
Rwanda - 14.104969
Benin - 13.22486
Burundi - 12.332788
Tunisia - 11.972169
Jordan - 11.937
Belgium - 11.930567
Haiti - 11.867032
Bolivia - 11.365333
United Arab Emirates - 11.294243
Czechia - 10.915839
Dominican Republic - 10.771504
Portugal - 10.749635
Sweden - 10.604464
Tajikistan - 10.499
Greece - 10.372335
Azerbaijan - 10.259701
Israel - 10.1967
Papua New Guinea - 10.185363
Honduras - 9.892632
Cuba - 9.748007
Hungary - 9.489
Austria - 9.219113
Belarus - 9.10928
Switzerland - 9.124288
Sierra Leone - 9.077691
Togo - 8.095498
Laos - 7.647
Hong Kong(China) - 7.5108
Libya - 7.459
Kyrgyzstan - 7.4043
Turkmenistan - 7.057841
Nicaragua - 6.874748
Serbia - 6.567783
Central African Republic - 6.470307
Bulgaria - 6.43736
Congo - 6.14218
Singapore - 6.1102
Paraguay - 6.109644
El Salvador - 6.029976
Denmark - 6.028459
Finland - 5.656779
Norway - 5.6274
Lebanon - 5.49
Palestine - 5.48345
Ireland - 5.4586
Slovakia - 5.409407
Oman - 5.359557
New Zealand - 5.342
Liberia - 5.248621
Costa Rica - 5.191824
Mauritania - 4.927532
Kuwait - 4.881254
Panama - 4.06478
Croatia - 3.866233
Georgia - 3.7045
Eritrea - 3.607
Mongolia - 3.544835
Uruguay - 3.485931
Bosnia and Herzegovina - 3.412
Qatar - 3.214609
Puerto Rico(US) - 3.184195
Armenia - 3.0762
Namibia - 3.022401
Lithuania - 2.885752
Jamaica - 2.774538
Gabon - 2.469296
Gambia - 2.422712
Moldova - 2.3813
Albania - 2.363314
Botswana - 2.359609
Slovenia - 2.133852
Lesotho - 2.116427
Guinea-Bissau - 1.852784
Latvia - 1.8235
North Macedonia - 1.822612
Equatorial Guinea - 1.668768
Bahrain - 1.594654
Kosovo - 1.585566
Timor-Leste - 1.391221
Trinidad and Tobago - 1.367764
Estonia - 1.362954
Mauritius - 1.241856
Eswatini - 1.235549
Djibouti - 1.066809
Cyprus - 0.983
Guyana - 0.956044
Comoros - 0.944388
Fiji - 0.902623
Bhutan - 0.784043
Solomon Islands - 0.750325
Macau(China) - 0.6889
Luxembourg - 0.681973
Montenegro - 0.623327
Suriname - 0.6165
Western Sahara(disputed) - 0.600904
Malta - 0.57425
Maldives - 0.515132
Cape Verde - 0.491233
Northern Cyprus - 0.476214
Brunei - 0.4555
Belize - 0.417634
Bahamas - 0.398165
Iceland - 0.39453
Transnistria - 0.367776
Vanuatu - 0.321409
French Polynesia(France) - 0.2795
Barbados - 0.2678
New Caledonia(France) - 0.264596
Abkhazia - 0.244236
São Tomé and Príncipe - 0.209607
Samoa - 0.205557
Saint Lucia - 0.1841
Curaçao(Netherlands) - 0.156115
Guam(US) - 0.153836
Seychelles - 0.123097
Kiribati - 0.12074
Saint Vincent and the Grenadines - 0.110872
Aruba(Netherlands) - 0.109435
Grenada - 0.109021
Antigua and Barbuda - 0.103603
Jersey(UK) - 0.103267
Tonga - 0.100179
Andorra - 0.089365
Cayman Islands(UK) - 0.088833
U.S. Virgin Islands(US) - 0.087146
Isle of Man(UK) - 0.084975
Micronesia - 0.075817
Dominica - 0.071946
Guernsey(UK) - 0.064781
Bermuda(UK) - 0.064055
Greenland(Denmark) - 0.05674
South Ossetia - 0.05652
Faroe Islands(Denmark) - 0.055064
Saint Kitts and Nevis - 0.05132
Turks and Caicos Islands(UK) - 0.050828
American Samoa(US) - 0.04971
Northern Mariana Islands(US) - 0.047329
Marshall Islands - 0.042418
Sint Maarten(Netherlands) - 0.041349
Liechtenstein - 0.041237
British Virgin Islands(UK) - 0.039471
Monaco - 0.038857
Gibraltar(UK) - 0.038196
San Marino - 0.034172
Saint Martin(France) - 0.031496
Palau - 0.016733
Anguilla(UK) - 0.01601
Cook Islands(New Zealand) - 0.01504
Nauru - 0.01168
Wallis and Futuna(France) - 0.01162
Tuvalu - 0.010643
Saint Barthélemy(France) - 0.010562
Saint Pierre and Miquelon(France) - 0.005819
Saint Helena, Ascension and Tristan da Cunha(UK) - 0.005651
Montserrat(UK) - 0.004386
Falkland Islands(UK) - 0.003662
Tokelau(New Zealand) - 0.002608
Norfolk Island(Australia) - 0.002188
Christmas Island(Australia) - 0.001692
Niue(New Zealand) - 0.001681
Vatican City - 0.000882
Cocos (Keeling) Islands(Australia) - 0.000593
Pitcairn Islands(UK) - 3.5e-05